# Generated by Django 4.2.11 on 2024-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="Profile",
            new_name="profile",
        ),
    ]
